include: package:lints/recommended.yaml

analyzer:
  plugins:
    - dart_code_metrics
  errors:
    # Promocionar estas advertencias a errores para que sean detectables.
    unused_local_variable: error
    unused_import: error
    unused_element: error
    dead_code: error
    unused_field: error

dart_code_metrics:
  anti-patterns:
    - long-method
    - long-parameter-list
  metrics:
    cyclomatic-complexity: 20
    lines-of-code: 50
    number-of-parameters: 4
    source-lines-of-code: 50
  rules:
    - no-boolean-literal-compare
    - no-empty-block
    - prefer-trailing-comma
    - prefer-conditional-expressions
    - no-equal-then-else
    - no-magic-number
    # Esta es la regla clave para detectar código público no utilizado.
    - no-unused-code
